# @package dataset
defaults:
  - nlp/hf_default
_target_: lightning_transformers.task.nlp.huggingface.language_modeling.LanguageModelingTransformerDataModule
cfg:
  dataset_name: wikitext
  dataset_config_name: wikitext-2-raw-v1
  block_size: 512
