# @package dataset
_target_: lightning_transformers.task.multiple_choice.LitSwagMultipleChoiceTransformerDataModule
dataset_name: swag
train_file: ''
validation_file: ''
dataset_config_name: 'regular'
padding: 'max_length'
truncation: 'only_first'
max_seq_length: 128
max_length: 128
preprocessing_num_workers: 8
load_from_cache_file: True
pad_to_max_length: True