# @package task
_target_: lightning_transformers.task.huggingface.language_modeling.LanguageModelingTransformer
backbone:
  downstream_model_type: transformers.AutoModelForCausalLM
  pretrained_model_name_or_path: bert-base-cased
optimizer: ${optimizer}
scheduler: ${scheduler}