# @package task
defaults:
  - backbone: huggingface/bert-base-cased
_target_: lightning_transformers.task.language_modeling.LitLanguageModelingTransformer
downstream_model_type: transformers.AutoModelForCausalLM
