# @package task
defaults:
  - /backbone@_group_: huggingface/bert-base-cased
_target_: lightning_transformers.task.language_modeling.LanguageModelingTransformer
downstream_model_type: transformers.AutoModelForCausalLM
