# @package task
defaults:
  - /backbone@_group_: huggingface/bert-base-cased
_target_: lightning_transformers.task.multiple_choice.LitAutoModelMultipleChoiceTransformer
downstream_model_type: transformers.AutoModelForMultipleChoice
