# @package task
defaults:
  - backbone: huggingface/bert-base-cased
_target_: lightning_transformers.task.question_answering.LitAutoModelQuestionAnsweringTransformer
downstream_model_type: transformers.AutoModelForQuestionAnswering
