# @package task
_target_: lightning_transformers.task.huggingface.summarization.HFSummarizationTransformer
downstream_model_type: transformers.AutoModelForSeq2SeqLM
backbone: ${backbone}
optimizer: ${optimizer}
scheduler: ${scheduler}
cfg:
  use_stemmer: True
  rouge_newline_sep: True
  val_target_max_length: 142
  num_beams: null
  compute_generate_metrics: True
