# @package task
defaults:
  - /backbone@_group_: huggingface/bert-base-cased
_target_: lightning_transformers.task.huggingface.text_classification.LitAutoModelTextClassificationTransformer
downstream_model_type: transformers.AutoModelForSequenceClassification