_target_: lightning_transformers.huggingface.task.text_classification.TextClassificationTransformer
downstream_model_type: transformers.AutoModelForSequenceClassification
pretrained_model_name_or_path: bert-base-cased