# @package task
defaults:
  - backbone: huggingface/bert-base-cased
_target_: lightning_transformers.task.text_classification.LitAutoModelTextClassificationTransformer
downstream_model_type: transformers.AutoModelForSequenceClassification