# @package dataset
defaults:
  - /dataset/nlp/default
_target_: lightning_transformers.task.nlp.huggingface.text_classification.TextClassificationDataModule
cfg:
  dataset_name: emotion
  dataset_config_name: null
  train_file: ''
  validation_file: ''
  cache_dir: null
  padding: 'max_length'
  truncation: 'only_first'
  preprocessing_num_workers: 8
  load_from_cache_file: True
  max_length: 128
