# @package dataset
defaults:
  - nlp/hf_default
_target_: lightning_transformers.task.nlp.huggingface.summarization.CNNDailyMailSummarizationDataModule
cfg:
  dataset_name: cnn_dailymail
  dataset_config_name: 3.0.0
  max_source_length: 1024
  max_target_length: 128
