defaults: # for loading the default config
  
  - model: bert-base-uncased
  - dataset: squad
  - training: default
  - trainer: debug
  - scheduler: linear_schedule_with_warmup
  - optimizer: adamw

task: ???