# @package dataset
_target_: lightning_transformers.task.huggingface.text_classification.TextClassificationDataModule
dataset_name: emotion
train_file: ''
validation_file: ''
padding: 'max_length'
truncation: 'only_first'
preprocessing_num_workers: 8
load_from_cache_file: True
