# @package dataset
defaults:
  - nlp/hf_default
_target_: lightning_transformers.task.nlp.multiple_choice.SwagMultipleChoiceTransformerDataModule
cfg:
  dataset_name: swag
  dataset_config_name: 'regular'
  padding: False
