defaults:
  - default # add args from default trainer conf
  - override /optimizer@_group_: deepspeed/cpu_adam # default to DeepSpeed CPU Adam
gpus: 1
accelerator: deepspeed
precision: 16
plugins:
  _target_: pytorch_lightning.plugins.DeepSpeedPlugin
  stage: 2
  cpu_offload: True
