# @package task
defaults:
  - /task/nlp/huggingface/default
_target_: lightning_transformers.task.nlp.huggingface.language_modeling.LanguageModelingTransformer
downstream_model_type: transformers.AutoModelForCausalLM
