# @package task
defaults:
  - nlp/huggingface/default
_target_: lightning_transformers.task.nlp.huggingface.text_classification.TextClassificationTransformer
downstream_model_type: transformers.AutoModelForSequenceClassification
