# @package task
defaults:
  - nlp/huggingface/default
_target_: lightning_transformers.task.nlp.huggingface.translation.HFTranslationTransformer
downstream_model_type: transformers.AutoModelForSeq2SeqLM
cfg:
  n_gram: 4
  smooth: False
  val_target_max_length: 142
  num_beams: null
  compute_generate_metrics: True
